{{- if .Values.arcalos }}
apiVersion: v1
data:
  arcalos_beta_preview_sa: {{ .Values.arcalos.arcalosBetaPreviewSA | quote }}
kind: Secret
metadata:
  name:  arcalos-beta-preview-secret
type: Opaque
{{- end }}
