---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arcalos-cleanup-config
data:
  entrypoint.sh: |-
    #!/bin/bash
    jx step git credentials
   
    gcloud auth activate-service-account --key-file $GKE_SA_KEY_FILE
 
    git clone https://github.com/cloudbees/arcalos
    cd arcalos

    ./cleanup.sh
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-arcalos-cleanup
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: arcalos-cleanup
            release: jx
        spec:
          containers:
          - command:
            - /bin/entrypoint.sh
            env:
            - name: GKE_SA_KEY_FILE
              value: "/secret/sa/ci_bot.json"
            image: gcr.io/jenkinsxio/builder-go:2.0.838-196
            imagePullPolicy: IfNotPresent
            name: arcalos-cleanup
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - name: sa
                mountPath: /secret
                readOnly: true
                subPath: ci_sa
              - name: cleanup-config
                mountPath: /bin/entrypoint.sh
                readOnly: true
                subPath: entrypoint.sh
          volumes:
            - name: sa
              secret:
                secretName: arcalos-secret
            - name: cleanup-config
              configMap:
                defaultMode: 0700
                name: arcalos-cleanup-config
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0/15 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
