apiVersion: v1
data:
  credentials: {{ .Values.AWSCreds.credentials | quote }}
  account_id: {{ .Values.AWSCreds.account_id   | quote }}
  vault_user: {{ .Values.AWSCreds.vault_user   | quote }}
kind: Secret
metadata:
  name: aws-bdd-user-creds
  namespace: jx
type: Opaque
