apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: gcs-copy
  name: copy-charts-index
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: prepare-chart-index
            # curl the index.yaml file from chartmuseum before attempting a copy. This causes it to regenerate.
            # No need to wait afterwards as the http call won't return until it's ready
            image: gcr.io/jenkinsxio/builder-go:0.1.658
            imagePullPolicy: IfNotPresent
            env:
              - name: URL
                value: http://jenkins-x-chartmuseum:8080/index.yaml
            command:
              # Runs curl and only outputs errors
              - curl
            args:
              - --show-error
              - --silent
              - --output
              - /dev/null
              - $(URL)
          containers:
          - command:
            - gcs-copy
            env:
            - name: BUCKET_NAME
              value: chartmuseum.jenkins-x.io
            - name: COPY_FROM
              value: charts/index-cache.yaml
            - name: COPY_TO
              value: index.yaml
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /gcs-jenkinsx-chartmuseum/gcs-chartmuseum.key.json
            image: jenkinsxio/gcs-copy:0.0.1
            imagePullPolicy: IfNotPresent
            name: copy-chart-index-to-gcs
            volumeMounts:
            - mountPath: /gcs-jenkinsx-chartmuseum
              name: gcs-jenkinsx-chartmuseum
              readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          volumes:
          - name: gcs-jenkinsx-chartmuseum
            secret:
              secretName: gcs-jenkinsx-chartmuseum
  schedule: '*/2 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
