apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-e2e-gc
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: e2e-gc
            release: jx
        spec:
          containers:
          - args:
            - step
            - e2e
            - gc
            - --project-id=jenkins-x-bdd3
            - --batch-mode
            command:
            - jx
            env:
            - name: JX_LOG_FORMAT
              value: json
            - name: GKE_SA_KEY_FILE
              value: "/builder/home/bdd-credentials.json"
            image: gcr.io/jenkinsxio/builder-go:2.1.20-646
            imagePullPolicy: IfNotPresent
            name: e2e-gc
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - name: bdd-secret
                mountPath: "/builder/home/"
                readOnly: true
          volumes:
            - name: bdd-secret
              secret:
                secretName: bdd-secret
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0/10 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
