  
{{- if .Values.JenkinsXGHEApproverTestUser }}
apiVersion: v1
data:
  password: {{ .Values.JenkinsXGHEApproverTestUser.password | b64enc | quote }} # pragma: allowlist secret
  username: {{ .Values.JenkinsXGHEApproverTestUser.username | b64enc | quote }}
kind: Secret
metadata:
  name: jx-pipeline-git-github-ghe-approver
  annotations:
    jenkins.io/credentials-description: API Token for acccessing https://github.beescloud.com
      Git service inside pipelines with a second user
    jenkins.io/foo: bar
    jenkins.io/name: GHE
    jenkins.io/url: https://github.beescloud.com
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
type: Opaque
{{- end }}
