{{- if .Values.JenkinsXGitLabApproverTestUser }}
apiVersion: v1
data:
  password: {{ .Values.JenkinsXGitLabApproverTestUser.password | b64enc | quote }} # pragma: allowlist secret
  username: {{ .Values.JenkinsXGitLabApproverTestUser.username | b64enc | quote }}
kind: Secret
metadata:
  name:  jx-pipeline-git-gitlab-gl-approver
  annotations:
    jenkins.io/name: gl
    jenkins.io/url: https://gitlab.com
    jenkins.io/test: "true"
    jenkins.io/credentials-description: API Token for acccessing https://gitlab.com Git service for tests with a second user
  labels:
    jenkins.io/credentials-type: usernamePassword
type: Opaque
{{- end }}
