{{- if .Values.JenkinsXGKEServiceAccount }}
apiVersion: v1
data:
  filename: {{ .Values.JenkinsXGKEServiceAccount.filename | quote }}
  data: {{ .Values.JenkinsXGKEServiceAccount.data | quote }}
kind: Secret
metadata:
  labels:
    jenkins.io/credentials-type: secretFile
  name: gke-sa
type: Opaque
{{- end }}