apiVersion: jenkins.io/v1
kind: Scheduler
metadata:
  creationTimestamp: null
  name: jx-scheduler
spec:
  plugins:
    entries:
      - label
  postsubmits:
    replace: true
    entries:
    - agent: tekton
      branches:
        entries:
        - master
      cluster: ""
      context: ""
      labels: {}
      maxConcurrency: 0
      name: release
      report: false
      runIfChanged: ""
      skipBranches: {}
  presubmits:
    replace: true
    entries:
    - agent: tekton
      alwaysRun: true
      branches: {}
      cluster: ""
      context: integration
      labels: {}
      maxConcurrency: 0
      mergeMethod: ""
      name: integration
      optional: false
      policy:
        requiredStatusChecks:
          contexts:
            entries:
            - integration
      queries:
      - excludedBranches: {}
        includedBranches: {}
        labels:
          entries:
          - approved
          - lgtm
        milestone: ""
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
        reviewApprovedRequired: false
      report: true
      rerunCommand: /test integration
      runIfChanged: ""
      skipBranches: {}
      trigger: (?m)^/test( all| integration),?(\s+|$)
    - agent: tekton
      alwaysRun: true
      branches: {}
      cluster: ""
      context: bdd
      labels: {}
      maxConcurrency: 0
      mergeMethod: ""
      name: bdd
      optional: false
      policy:
        requiredStatusChecks:
          contexts:
            entries:
              - bdd
      queries:
        - excludedBranches: {}
          includedBranches: {}
          labels:
            entries:
              - approved
              - lgtm
          milestone: ""
          missingLabels:
            entries:
              - do-not-merge
              - do-not-merge/hold
              - do-not-merge/work-in-progress
              - needs-ok-to-test
              - needs-rebase
          reviewApprovedRequired: false
      report: true
      rerunCommand: /test bdd
      runIfChanged: ""
      skipBranches: {}
      trigger: (?m)^/test( all| bdd),?(\s+|$)