{{- if .Values.terraformGoogleJXSA }}
apiVersion: v1
data:
  terraform_google_jx_sa: {{ .Values.terraformGoogleJXSA | quote }}
kind: Secret
metadata:
  name:  terraform-secret
type: Opaque
{{- end }}
