
{{- if .Values.TestJenkinsUser }}
apiVersion: v1
data:
  username: {{ .Values.TestJenkinsUser.username | b64enc | quote }}
  password: {{ .Values.TestJenkinsUser.password | b64enc | quote }} # pragma: allowlist secret
kind: Secret
metadata:
  labels:
    jenkins.io/credentials-type: usernamePassword
  name: test-jenkins-user
type: Opaque
{{- end }}