apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-version-stream-update
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: jx-version-stream-update
            release: jx
        spec:
          containers:
          - args:
            - "jx step credential -s knative-git-user-pass -k - password -f /builder/home/git-token && jx step create pr versions --filter=\"*\" --images --excludes 'jetstack/cert-manager' --batch-mode"
            command:
            - /bin/bash
            - -c
            env:
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            image: gcr.io/jenkinsxio/builder-go:0.1.667
            imagePullPolicy: IfNotPresent
            name: jx-version-stream-update
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: tekton-bot
  schedule: 0 */12 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
