{{- if .Values.JenkinsXVersionsTestUser }}
apiVersion: v1
data:
  password: {{ .Values.JenkinsXVersionsTestUser.password | b64enc | quote }} # pragma: allowlist secret
  username: {{ .Values.JenkinsXVersionsTestUser.username | b64enc | quote }}
kind: Secret
metadata:
  name: jenkins-x-versions-bot-test-github
  annotations:
    jenkins.io/name: githubtest-versions
    jenkins.io/url: https://test.com
    jenkins.io/test: "true"
    jenkins.io/credentials-description: API Token for acccessing https://github.com Git service for tests
  labels:
    jenkins.io/created-by: jx
    jenkins.io/credentials-type: usernamePassword
type: Opaque
{{- end }}
