enabled: false

hmacToken: "{{ .Parameters.prow.hmacToken }}"
oauthToken: "{{ .Parameters.pipelineUser.token }}"
user: "{{ .Parameters.pipelineUser.username }}"

buildnum:
  enabled: false
pipelinerunner:
  args:
  - controller
  - pipelinerunner
  enabled: "false"
tillerNamespace: ""

sinker:
  replicaCount: 0

build:
  enabled: false
