apiVersion: jenkins.io/v1
kind: SourceRepositoryGroup
metadata:
  name: whitesource-group
spec:
  scheduler:
    apiVersion: jenkins.io/v1
    kind: Scheduler
    name: whitesource-scheduler
  repositories: 
  - name: jenkins-x-sso-operator
    kind: SourceRepository
  - name: jenkins-x-bucketrepo
    kind: SourceRepository
  - name: cloudbees-jx-tenant-service
    kind: SourceRepository
  - name: cloudbees-lighthouse-githubapp
    kind: SourceRepository
  - name: cloudbees-jx-repository-controller
    kind: SourceRepository
  - name: cloudbees-jx-arcalos-role-controller
    kind: SourceRepository
  - name: cloudbees-jx-segment-controller
    kind: SourceRepository
