adminUser:
  password: vault:tekton-weasel/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  token: vault:tekton-weasel/pipelineUser:token
  username: jenkins-x-bot
prow:
  hmacToken: vault:tekton-weasel/prow:hmacToken
sso:
  dashboardAuthID: vault:tekton-weasel/sso:authID
  dashboardAuthSecret: vault:tekton-weasel/sso:authSecret # pragma: allowlist secret
  dashboardAuthOrg: jenkins-x-dashboard